import React from "react";
import RelatedProductEntry from './RelatedProductEntry'

export default function RelatedItems(props) {
  const entry = props.products.map(product => (
    <div className="related-products-card" key={product.id}>
      <RelatedProductEntry product={product} />
    </div>
  ))

  return (
    <div className="related-products">
        <div className="related-products-list" >
          {entry}
        </div>
      <div className="related-products-user">
        <span>
          List of Products (generated by user)
        </span>
      </div>
    </div>
  )
}