import React from "react";
import RelatedProductEntry from './RelatedProductEntry'
import axios from 'axios';
import Options from '../../config.js';

export default function RelatedItems(props) {

  const [relatedItems, setRelatedItems] = React.useState([])

  React.useEffect(() => {
      axios.get(`${Options.URL}/products/${props.selected.id}/related`, {
        headers: {
          Authorization: Options.TOKEN
        }
      }).then((res) => {
        let related = props.products.filter(item => res.data.includes(item.id))
        setRelatedItems(related)
      })
   }, [])

  const entry = relatedItems.map(product => (
    <div className="related-products-card" key={product.id}>
      <RelatedProductEntry related={product}/>
    </div>
  ))

  return (
    <div className="related-products">
      <div className="sectionTitle">RELATED ITEMS</div>
        <div className="related-products-list" >
          {entry}
        </div>
      <div className="related-products-user">
        <span>
          List of Products (generated by user)
        </span>
      </div>
    </div>
  )
}